name: sync images

on:
  push:
    branches:
      - publish
      - feature/mcr

env:
  DOCKERHUB_USERNAME: newbe36524
  DOCKERHUB_NAMESPACE: newbe36524
  ALIYUN_USERNAME: pianzide1117
  ALIYUN_NAMESPACE: newbe36524
  TENCENTYUN_USERNAME: 472158246
  TENCENTYUN_NAMESPACE: mcr_newbe36524
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update auth.json
        run: |
          sed -i "s#DOCKERHUB_USERNAME#${DOCKERHUB_USERNAME}#g" auth.json
          sed -i "s#DOCKERHUB_TOKEN#${{ secrets.DOCKERHUB_TOKEN }}#g" auth.json
          sed -i "s#ALIYUN_USERNAME#${ALIYUN_USERNAME}#g" auth.json
          sed -i "s#ALIYUN_TOKEN#${{ secrets.ALIYUN_TOKEN }}#g" auth.json
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: pip install
        run: |
          pip install pipenv
      - name: pull and sync
        run: |
          pipenv run sync
